export const NEW_PROJECT      = 'NEW_PROJECT';
export const DELETE_PROJECT   = 'DELETE_PROJECT';
export const EDIT_PROJECT     = 'EDIT_PROJECT';
export const PLAY_PROJECT     = 'PLAY_PROJECT';
export const SELECT_PROJECT   = 'SELECT_PROJECT';
export const SHARE_PROJECT    = 'SHARE_PROJECT';

export const SOCKET_CONNECT          = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT       = 'SOCKET_DISCONNECT';
export const SOCKET_RECONNECT        = 'SOCKET_RECONNECT';
export const SOCKET_RECONNECTING     = 'SOCKET_RECONNECTING';
export const SOCKET_RECONNECT_ERROR  = 'SOCKET_RECONNECT_ERROR';
export const SOCKET_RECONNECT_FAILED = 'SOCKET_RECONNECT_FAILED';
export const SOCKET_ERROR            = 'SOCKET_ERROR';

export const IMPRESS_NEXT = 'IMPRESS_NEXT';
export const IMPRESS_PREV = 'IMPRESS_PREV';
export const IMPRESS_GOTO = 'IMPRESS_GOTO';
