export const NEW_PRESENTATION    = 'NEW_PRESENTATION';
export const DELETE_PRESENTATION = 'DELETE_PRESENTATION';
export const EDIT_PRESENTATION   = 'EDIT_PRESENTATION';
export const PLAY_PRESENTATION   = 'PLAY_PRESENTATION';
export const SELECT_PRESENTATION = 'SELECT_PRESENTATION';
